### PR TITLE
Everything

### PR DESCRIPTION
**Pull request by randomtestfive**
Functionally the same as the python version, except for basemod install.

### CODE REVIEW

**Comment by LewisTehMinerz** [comment]
So this will be able to install mods?

**Comment by williambl** [comment]
Looking at the code, I think so. The code looks almost identical to the python edition.

**Comment by randomtestfive** [comment]
Everything's there except for basemod install, I couldn't decipher what it was doing. There's also a release with the jar on my fork.

**Comment by williambl** [comment]
@randomtestfive basically it unzips both jars, merges the mod into minecraft.jar, then zips them back up into a jar.

Also, your profile picture appears to be empty. (SeeWhatIDidThere)

**Comment by randomtestfive** [comment]
Also, if you just get the jar, it will say there's something wrong with the url because its looking in the main place that doesn't have a version.txt.

**Comment by LewisTehMinerz** [comment]
It merges the mods into the minecraft.jar? What about MCForge mods?

**Comment by williambl** [comment]
Forge mods go into the modsfolder, if forge is present.

**Comment by randomtestfive** [comment]
It should be able to install basemods now, but I'm not sure, I can't test it.

**Comment by randomtestfive** [comment]
New release, with basemod and an icon.

**Comment by LewisTehMinerz** [comment]
You have been invited as a collaborator. You have shown to be a good member of the team. (also, merged)

**Comment by LewisTehMinerz** [comment]
Note: This pull request was accepted BEFORE the stable and nightly branches were made. Do not create any pull requests on STABLE as they will be denied without consideration. Only make pull requests on NIGHTLY.

**Pull request merged**
