### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by randomtestfive**
Merge all of the bugfixes into stable before adding too many features on top.

### CODE REVIEW

**Comment by randomtestfive** [comment]
@LewisTehMinerz, if this looks good, I can get it merged.

**Comment by LewisTehMinerz** [comment]
Cannot merge. Branch has conflicts.

**Comment by randomtestfive** [comment]
Thats what the .gitattributes was for, I can merge it manually.

**Comment by LewisTehMinerz** [comment]
Note: This pull request is pulling a FINALIZED VERSION OF CMAN FROM THE NIGHTLY BRANCH.
Do not create any pull requests on STABLE as they will be denied without consideration. Only make pull requests on NIGHTLY.

**Pull request merged**
